CREATE TABLE IF NOT EXISTS PUBLIC.ROLES
(
    ID              INTEGER         AUTO_INCREMENT  NOT NULL,
    NAME            VARCHAR(255)    NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.PERMISSIONS
(
    ID              INTEGER         AUTO_INCREMENT  NOT NULL,
    NAME            VARCHAR(255)    NOT NULL UNIQUE,
    DESCRIPTION     VARCHAR(255)    NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.ROLEHASPERMISSIONS
(
    ID              INTEGER     AUTO_INCREMENT  NOT NULL,
    ROLEID          INTEGER     NOT NULL,
    PERMISSIONID    INTEGER     NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (ROLEID, PERMISSIONID),
    FOREIGN KEY (ROLEID) REFERENCES PUBLIC.ROLES(ID),
    FOREIGN KEY (PERMISSIONID) REFERENCES PUBLIC.PERMISSIONS(ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.USERS
(
    ID              INTEGER     AUTO_INCREMENT NOT NULL,
    USERNAME        VARCHAR(255) NOT NULL UNIQUE,
    EMAIL           VARCHAR(255) NOT NULL UNIQUE,
    PASSWORD        VARCHAR(255) NOT NULL, /*hashed password*/
    ROLEID          INTEGER NOT NULL,
    SCORE           INTEGER,
    PRIMARY KEY (ID),
    FOREIGN KEY (ROLEID) REFERENCES PUBLIC.ROLES(ID)
);

