spring:
  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        auto_quote_keyword: true
        dialect: org.hibernate.dialect.H2Dialect

logging:
  file.name: ./logs/backend.log
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE